{
 "title": "Erigon",
 "tags": [
  "eth1.0",
  "ethereum",
  "erigon"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(sync{}, namespace)"
    }
   },
   { "name": "pod", "label": "pod", "query": { "query": "label_values(sync{}, pod)" } },
   { "name": "quantile", "query": "0.5, 0.9, 0.97, 0.99, 1" },
   {
    "name": "rate_interval",
    "label": "Rate Interval",
    "query": "1m,10m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Blocks execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sync Stages progress",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sync{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{stage}}: {{pod}}"
    }
   ]
  },
  {
   "title": "Sync Stages progress rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(sync{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
     "legendFormat": "{{stage}}:  {{pod}}"
    }
   ]
  },
  {
   "title": "Block Execution speed ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chain_execution_seconds{quantile=\"$quantile\",namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "execution: {{pod}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Commit",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(db_commit_seconds_count{phase=\"total\",namespace=\"$namespace\",pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "commit: {{pod}}"
    }
   ]
  },
  {
   "title": "Commit speed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "db_commit_seconds{phase=\"total\",quantile=\"$quantile\",namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "commit_total: {{pod}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"gc\",quantile=\"$quantile\",namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "commit_gc: {{pod}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"write\",quantile=\"$quantile\",namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "commit_write: {{pod}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"sync\",quantile=\"$quantile\",namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "commit_sync: {{pod}}"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "db_size{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "size: {{pod}}"
    }
   ]
  },
  {
   "title": "GC and State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "db_gc_leaf{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "gc_leaf: {{pod}}"
    },
    {
     "expr": "db_gc_overflow{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "gc_overflow: {{pod}}"
    },
    {
     "expr": "db_state_leaf{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "state_leaf: {{pod}}"
    },
    {
     "expr": "db_state_branch{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "state_branch: {{pod}}"
    }
   ]
  },
  {
   "title": "DB Pages Ops/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(db_pgops_clone{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
     "legendFormat": "clone: {{pod}}"
    },
    {
     "expr": "rate(db_pgops_split{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
     "legendFormat": "split: {{pod}}"
    },
    {
     "expr": "rate(db_pgops_spill{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
     "legendFormat": "spill: {{pod}}"
    },
    {
     "expr": "rate(db_pgops_wops{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
     "legendFormat": "wops: {{pod}}"
    },
    {
     "expr": "rate(db_pgops_unspill{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
     "legendFormat": "unspill: {{pod}}"
    }
   ]
  },
  {
   "title": "Tx Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "tx_limit{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "limit: {{pod}}"
    },
    {
     "expr": "tx_dirty{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "dirty: {{pod}}"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Rusage Total (\"last value\" - \"first value\" on selected period)",
   "type": "stat",
   "gridPos": { "h": 18, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "ru_inblock{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "inblock: {{pod}}"
    },
    {
     "expr": "ru_outblock{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "outblock: {{pod}}"
    },
    {
     "expr": "ru_minflt{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "minflt: {{pod}}"
    },
    {
     "expr": "ru_majflt{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "majflt: {{pod}}"
    },
    {
     "expr": "system_disk_readbytes{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "system_disk_readbytes: {{pod}}"
    },
    {
     "expr": "system_disk_writebytes{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "system_disk_writebytes: {{pod}}"
    },
    {
     "expr": "db_pgops_newly{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "pgops_newly: {{pod}}"
    },
    {
     "expr": "db_pgops_cow{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "pgops_cow: {{pod}}"
    },
    {
     "expr": "db_pgops_clone{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "pgops_clone: {{pod}}"
    },
    {
     "expr": "db_pgops_split{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "pgops_split: {{pod}}"
    },
    {
     "expr": "db_pgops_merge{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "pgops_merge: {{pod}}"
    },
    {
     "expr": "db_pgops_spill{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "pgops_spill: {{pod}}"
    },
    {
     "expr": "db_pgops_unspill{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "pgops_unspill: {{pod}}"
    },
    {
     "expr": "db_pgops_wops{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "pgops_wops: {{pod}}"
    }
   ]
  },
  {
   "title": "Read/Write syscall/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(process_io_write_syscalls_total{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
     "legendFormat": "in: {{pod}}"
    },
    {
     "expr": "rate(process_io_read_syscalls_total{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
     "legendFormat": "out: {{pod}}"
    }
   ]
  },
  {
   "title": "getrusage: minflt - soft page faults (reclaims), majflt - hard faults",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(process_minor_pagefaults_total{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
     "legendFormat": "soft: {{pod}}"
    },
    {
     "expr": "rate(process_major_pagefaults_total{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
     "legendFormat": "hard: {{pod}}"
    }
   ]
  },
  {
   "title": "Disk bytes/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(process_io_storage_read_bytes_total{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
     "legendFormat": "read: {{pod}}"
    },
    {
     "expr": "rate(process_io_storage_written_bytes_total{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
     "legendFormat": "write: {{pod}}"
    }
   ]
  },
  {
   "title": "cgo calls",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(go_cgo_calls_count{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
     "legendFormat": "go_cgo_calls_count: {{pod}}"
    }
   ]
  },
  {
   "title": "go memstat",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_sys_bytes{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "go_memstats_stack_sys_bytes"
    },
    {
     "expr": "go_memstats_sys_bytes{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "go_memstats_sys_bytes"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "go_memstats_stack_inuse_bytes"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "go_memstats_mspan_sys_bytes"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "go_memstats_mcache_sys_bytes"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_alloc_bytes"
    }
   ]
  },
  {
   "title": "GO Goroutines and Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "go/goroutines: {{pod}}"
    },
    {
     "expr": "go_threads{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "go/threads: {{pod}}"
    }
   ]
  },
  {
   "title": "mem: resident set size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "resident mem: {{pod}}"
    },
    {
     "expr": "mem_data{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "data: {{pod}}"
    },
    {
     "expr": "mem_stack{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "stack: {{pod}}"
    },
    {
     "expr": "mem_locked{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "locked: {{pod}}"
    },
    {
     "expr": "mem_swap{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "swap: {{pod}}"
    }
   ]
  },
  {
   "title": "Host VMem",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vmem_total{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "total: {{pod}}"
    },
    {
     "expr": "vmem_available{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "available: {{pod}}"
    },
    {
     "expr": "vmem_used{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "used: {{pod}}"
    },
    {
     "expr": "vmem_buffers{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "buffers: {{pod}}"
    },
    {
     "expr": "vmem_cached{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "cached: {{pod}}"
    },
    {
     "expr": "vmem_writeback{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "writeback: {{pod}}"
    },
    {
     "expr": "vmem_dirty{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "dirty: {{pod}}"
    },
    {
     "expr": "vmem_shared{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "shared: {{pod}}"
    },
    {
     "expr": "vmem_mapped{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "mapped: {{pod}}"
    }
   ]
  },
  {
   "title": "GC Stop the World per sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds{quantile=\"0.75\",namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])"
    }
   ]
  },
  {
   "title": "Process Mem: allocate objects/sec, free",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
     "legendFormat": "go_memstats_mallocs_total"
    },
    {
     "expr": "rate(go_memstats_frees_total{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
     "legendFormat": "go_memstats_frees_total"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_system_total{namespace=\"$namespace\",pod=~\"$pod\"}[1m])",
     "legendFormat": "system: {{pod}}"
    },
    {
     "expr": "increase(process_cpu_seconds_user_total{namespace=\"$namespace\",pod=~\"$pod\"}[1m])",
     "legendFormat": "iowait: {{pod}}"
    }
   ]
  },
  {
   "title": "TxPool v2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Timings",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "pool_process_remote_txs{quantile=\"$quantile\",namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "process_remote_txs: {{pod}}"
      },
      {
       "expr": "pool_add_remote_txs{quantile=\"$quantile\",namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "add_remote_txs: {{pod}}"
      },
      {
       "expr": "pool_new_block{quantile=\"$quantile\",namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "new_block: {{pod}}"
      },
      {
       "expr": "pool_write_to_db{quantile=\"$quantile\",namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "write_to_db: {{pod}}"
      },
      {
       "expr": "pool_propagate_to_new_peer{quantile=\"$quantile\",namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "propagate_to_new_peer: {{pod}}"
      },
      {
       "expr": "pool_propagate_new_txs{quantile=\"$quantile\",namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "propagate_new_txs: {{pod}}"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(pool_process_remote_txs_count{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
       "legendFormat": "pool_process_remote_txs_count: {{pod}}"
      },
      {
       "expr": "rate(pool_add_remote_txs_count{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
       "legendFormat": "pool_add_remote_txs_count: {{pod}}"
      },
      {
       "expr": "rate(pool_new_block_count{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
       "legendFormat": "pool_new_block_count: {{pod}}"
      },
      {
       "expr": "rate(pool_write_to_db_count{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
       "legendFormat": "pool_write_to_db_count: {{pod}}"
      }
     ]
    },
    {
     "title": "Cache hit-rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "sum(delta(cache_total{result=\"hit\",name=\"txpool\",namespace=\"$namespace\",pod=~\"$pod\"}[1m]))/sum(delta(cache_total{name=\"txpool\",namespace=\"$namespace\",pod=~\"$pod\"}[1m])) ",
       "legendFormat": "hit rate: {{pod}} "
      }
     ]
    },
    {
     "title": "Cache rps",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 61 },
     "targets": [
      {
       "expr": "rate(cache_total{name=\"txpool\",namespace=\"$namespace\",pod=~\"$pod\"}[1m])",
       "legendFormat": "{{result}}: {{pod}} "
      },
      {
       "expr": "rate(cache_timeout_total{name=\"txpool\",namespace=\"$namespace\",pod=~\"$pod\"}[1m])",
       "legendFormat": "timeout: {{pod}} "
      }
     ]
    },
    {
     "title": "Cache keys",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cache_keys_total{name=\"txpool\",namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "keys: {{pod}} "
      },
      {
       "expr": "cache_list_total{name=\"txpool\",namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "list: {{pod}} "
      }
     ]
    },
    {
     "title": "DB",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(pool_write_to_db_bytes{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
       "legendFormat": "pool_write_to_db_bytes: {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(rpc_duration_seconds_count{instance=~\"$instance\",success=\"success\"}[1m])",
       "legendFormat": "success {{method}} {{pod}} "
      },
      {
       "expr": "rate(rpc_duration_seconds_count{instance=~\"$instance\",success=\"failure\"}[1m])",
       "legendFormat": "failure {{method}} {{pod}} "
      }
     ]
    },
    {
     "title": "DB begin",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "db_begin_seconds{quantile=\"$quantile\",namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "db_begin_seconds: {{method}} {{pod}}"
      }
     ]
    },
    {
     "title": "Timings",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rpc_duration_seconds{quantile=\"$quantile\",namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": " {{method}} {{pod}} {{success}}"
      }
     ]
    },
    {
     "title": "GO Goroutines and Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "go_goroutines{namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "go/goroutines: {{pod}}"
      },
      {
       "expr": "go_threads{namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "go/threads: {{pod}}"
      }
     ]
    },
    {
     "title": "Cache keys",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cache_keys_total{name=\"rpc\",namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "keys: {{pod}} "
      },
      {
       "expr": "cache_list_total{name=\"rpc\",namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "list: {{pod}} "
      },
      {
       "expr": "cache_code_keys_total{name=\"rpc\",namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "code_keys: {{pod}} "
      },
      {
       "expr": "cache_code_list_total{name=\"rpc\",namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "code_list: {{pod}} "
      }
     ]
    },
    {
     "title": "Cache hit-rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 70 },
     "targets": [
      {
       "expr": "sum(delta(cache_total{result=\"hit\",name=\"rpc\",namespace=\"$namespace\",pod=~\"$pod\"}[1m]))/sum(delta(cache_total{name=\"rpc\",namespace=\"$namespace\",pod=~\"$pod\"}[1m])) ",
       "legendFormat": "hit rate: {{pod}} "
      },
      {
       "expr": "sum(delta(cache_code_total{result=\"hit\",name=\"rpc\",namespace=\"$namespace\",pod=~\"$pod\"}[1m]))/sum(delta(cache_code_total{name=\"rpc\",namespace=\"$namespace\",pod=~\"$pod\"}[1m])) ",
       "legendFormat": "code hit rate: {{pod}} "
      }
     ]
    },
    {
     "title": "gRPC call, error rates ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (grpc_service, grpc_method, instance) (rate(grpc_server_started_total{namespace=\"$namespace\",pod=~\"$pod\"}[1m]))",
       "legendFormat": "Calls: {{grpc_service}}.{{grpc_method}}, {{pod}}"
      },
      {
       "expr": "sum by (grpc_service, grpc_method, instance) (rate(grpc_server_handled_total{instance=~\"$instance\",grpc_code!=\"OK\"}[1m])) ",
       "legendFormat": "Errors: {{grpc_service}}.{{grpc_method}}, {{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(p2p_ingress{namespace=\"$namespace\",pod=~\"$pod\"}[$rate_interval])",
     "legendFormat": "ingress: {{pod}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "p2p_peers{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "peers: {{pod}}"
    },
    {
     "expr": "rate(p2p_dials{namespace=\"$namespace\",pod=~\"$pod\"}[1m])",
     "legendFormat": "dials: {{pod}}"
    },
    {
     "expr": "rate(p2p_serves{namespace=\"$namespace\",pod=~\"$pod\"}[1m])",
     "legendFormat": "serves: {{pod}}"
    }
   ]
  },
  {
   "title": "Blockchain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latest header",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "stage_headers{namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "Header: {{pod}}"
      }
     ]
    },
    {
     "title": "Latest receipt",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "chain_head_receipt{namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Latest block",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "stage_headers{namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "blocks:{{pod}}"
      }
     ]
    },
    {
     "title": "Executable transactions",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "txpool_pending{namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Gapped transactions",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "txpool_queued{namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Local transactions",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "txpool_local{namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Chain head",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "chain_head_header{namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "header: {{pod}}"
      },
      {
       "expr": "chain_head_receipt{namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "receipt: {{pod}}"
      },
      {
       "expr": "chain_head_block{namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "block: {{pod}}"
      }
     ]
    },
    {
     "title": "Transaction pool",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "txpool_pending{namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "executable: {{pod}}"
      },
      {
       "expr": "txpool_queued{namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "gapped: {{pod}}"
      },
      {
       "expr": "txpool_local{namespace=\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "local: {{pod}}"
      }
     ]
    },
    {
     "title": "Transaction propagation",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(txpool_valid{namespace=\"$namespace\",pod=~\"$pod\"}[1m])",
       "legendFormat": "valid: {{pod}}"
      },
      {
       "expr": "rate(txpool_invalid{namespace=\"$namespace\",pod=~\"$pod\"}[1m])",
       "legendFormat": "invalid: {{pod}}"
      },
      {
       "expr": "rate(txpool_underpriced{instance=\"$instance\"}[1m])",
       "legendFormat": "underpriced"
      },
      {
       "expr": "rate(txpool_pending_discard{instance=\"$instance\"}[1m])",
       "legendFormat": "executable discard"
      },
      {
       "expr": "rate(txpool_pending_replace{instance=\"$instance\"}[1m])",
       "legendFormat": "executable replace"
      },
      {
       "expr": "rate(txpool_pending_ratelimit{instance=\"$instance\"}[1m])",
       "legendFormat": "executable ratelimit"
      },
      {
       "expr": "rate(txpool_pending_nofunds{instance=\"$instance\"}[1m])",
       "legendFormat": "executable nofunds"
      },
      {
       "expr": "rate(txpool_queued_discard{instance=\"$instance\"}[1m])",
       "legendFormat": "gapped discard"
      },
      {
       "expr": "rate(txpool_queued_replace{instance=\"$instance\"}[1m])",
       "legendFormat": "gapped replace"
      },
      {
       "expr": "rate(txpool_queued_ratelimit{instance=\"$instance\"}[1m])",
       "legendFormat": "gapped ratelimit"
      },
      {
       "expr": "rate(txpool_queued_nofunds{instance=\"$instance\"}[1m])",
       "legendFormat": "gapped nofunds"
      }
     ]
    }
   ]
  }
 ]
}