{
 "title": "Nimbus",
 "tags": [
  "eth2.0",
  "ethereum",
  "nimbus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(nim_gc_mem_bytes,namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(nim_gc_mem_bytes,pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Slot",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_slot{namespace=\"$namespace\",pod=\"${pod}\"}"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_current_epoch{namespace=\"$namespace\",pod=\"${pod}\"}"
    }
   ]
  },
  {
   "title": "Current Justified Epoch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_current_justified_epoch{namespace=\"$namespace\",pod=\"${pod}\"}"
    }
   ]
  },
  {
   "title": "Last Finalized Epoch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_finalized_epoch{namespace=\"$namespace\",pod=\"${pod}\"}"
    }
   ]
  },
  {
   "title": "Open streams",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_open_streams{namespace=\"$namespace\",pod=\"${pod}\"}",
     "legendFormat": "{{type}} ({{dir}})"
    }
   ]
  },
  {
   "title": "version/network",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "version{namespace=\"$namespace\",pod=\"${pod}\"}",
     "legendFormat": "{{version}}"
    },
    {
     "expr": "network_name{namespace=\"$namespace\",pod=\"${pod}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{namespace=\"$namespace\",pod=\"${pod}\"}"
    }
   ]
  },
  {
   "title": "Att'ns Sent #all",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(beacon_attestations_sent_total)"
    }
   ]
  },
  {
   "title": "Att'ns Recv'd",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_attestations_received_total{namespace=\"$namespace\",pod=\"${pod}\"}"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_active_validators{namespace=\"$namespace\",pod=\"${pod}\"}",
     "legendFormat": "current validators"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval]) * 100",
     "legendFormat": "CPU usage %"
    },
    {
     "expr": "process_open_fds{namespace=\"$namespace\",pod=\"${pod}\"}",
     "legendFormat": "open file descriptors"
    },
    {
     "expr": "process_resident_memory_bytes{namespace=\"$namespace\",pod=\"${pod}\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(nim_gc_mem_bytes{namespace=\"$namespace\",pod=\"${pod}\"})",
     "legendFormat": "Nim GC mem total"
    },
    {
     "expr": "sum(nim_gc_mem_occupied_bytes{namespace=\"$namespace\",pod=\"${pod}\"})",
     "legendFormat": "Nim GC mem used"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_peers{namespace=\"$namespace\",pod=\"${pod}\"}",
     "legendFormat": "peers"
    },
    {
     "expr": "libp2p_pubsub_peers{namespace=\"$namespace\",pod=\"${pod}\"}",
     "legendFormat": "pubsub"
    },
    {
     "expr": "nbc_peers{namespace=\"$namespace\",pod=\"${pod}\"}",
     "legendFormat": "beacon_node"
    }
   ]
  },
  {
   "title": "Peer Type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_peers_identity{namespace=\"$namespace\",pod=\"${pod}\"}",
     "legendFormat": "{{agent}}"
    }
   ]
  },
  {
   "title": "GC Heap Objects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nim_gc_heap_instance_occupied_bytes{namespace=\"$namespace\",pod=\"${pod}\"}",
     "legendFormat": "{{type_name}}"
    }
   ]
  },
  {
   "title": "Incoming Traffic By Peer Type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(libp2p_peers_traffic_read_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "{{agent}}"
    }
   ]
  },
  {
   "title": "Blocks / Slot",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(beacon_blocks_received_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "received"
    },
    {
     "expr": "rate(beacon_blocks_proposed_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "proposed"
    }
   ]
  },
  {
   "title": "Outgoing Traffic By Peer Type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(libp2p_peers_traffic_write_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "{{agent}}"
    }
   ]
  },
  {
   "title": "Attestations / Slot",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(beacon_attestations_received_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "received"
    },
    {
     "expr": "rate(beacon_attestations_sent_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Mesh Health",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libp2p_gossipsub_healthy_peers_topics{namespace=\"$namespace\",pod=\"${pod}\"}",
     "legendFormat": "healthy"
    },
    {
     "expr": "libp2p_gossipsub_low_peers_topics{namespace=\"$namespace\",pod=\"${pod}\"}",
     "legendFormat": "low"
    },
    {
     "expr": "libp2p_gossipsub_no_peers_topics{namespace=\"$namespace\",pod=\"${pod}\"}",
     "legendFormat": "no peers"
    }
   ]
  },
  {
   "title": "aggregates/slot",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(beacon_aggregates_received_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Fanout Health",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nbc_gossipsub_healthy_fanout{namespace=\"$namespace\",pod=\"${pod}\"}",
     "legendFormat": "healthy"
    },
    {
     "expr": "nbc_gossipsub_good_fanout{namespace=\"$namespace\",pod=\"${pod}\"}",
     "legendFormat": "good"
    },
    {
     "expr": "nbc_gossipsub_low_fanout{namespace=\"$namespace\",pod=\"${pod}\"}",
     "legendFormat": "low"
    }
   ]
  },
  {
   "title": "Validator rewards / Epoch",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(attached_validator_balance_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval]) * 384 / 1000000000",
     "legendFormat": "GWei"
    }
   ]
  },
  {
   "title": "Discovery & Dialing",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_total_dial_attempts_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "dial attempts"
    },
    {
     "expr": "rate(discovery_message_requests_outgoing_total{instance=\"${instance}\",response!=\"no_response\"}[$__rate_interval])",
     "legendFormat": "discovery messages"
    },
    {
     "expr": "rate(libp2p_successful_dials_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "dial success"
    },
    {
     "expr": "rate(nbc_cycling_kicked_peers_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "kicked peers"
    }
   ]
  },
  {
   "title": "ETH1 Chain Length",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eth1_chain_len{namespace=\"$namespace\",pod=\"${pod}\"}",
     "legendFormat": "Eth1 chain len"
    }
   ]
  },
  {
   "title": "Pool Cached States",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "beacon_state_data_cache_hits_total{namespace=\"$namespace\",pod=\"${pod}\"} * 100 / (beacon_state_data_cache_hits_total{namespace=\"$namespace\",pod=\"${pod}\"} + beacon_state_data_cache_misses_total{namespace=\"$namespace\",pod=\"${pod}\"})",
     "legendFormat": "cache hit rate"
    }
   ]
  },
  {
   "title": "SQLite3",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sqlite3_memory_used_bytes{namespace=\"$namespace\",pod=\"${pod}\"}",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Batch Verifications/Slot",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(batch_verification_batches_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "batches"
    },
    {
     "expr": "rate(batch_verification_signatures_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "signatures"
    },
    {
     "expr": "rate(batch_verification_aggregates_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "aggregates"
    },
    {
     "expr": "rate(batch_verification_signatures_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval]) /\nrate(batch_verification_aggregates_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "sigs/aggregate"
    },
    {
     "expr": "rate(batch_verification_signatures_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval]) /\nrate(batch_verification_batches_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "sigs/batch"
    }
   ]
  },
  {
   "title": "Sync Committee msgs/slot",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(beacon_sync_committee_messages_received_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "messages"
    },
    {
     "expr": "rate(beacon_sync_committee_contributions_received_total{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "contributions"
    }
   ]
  },
  {
   "title": "Dropped msgs/slot (ignored/rejected)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(beacon_blocks_dropped_total{instance=\"${instance}\",reason=\"Ignore\"}[$__rate_interval])",
     "legendFormat": "blocks (I)"
    },
    {
     "expr": "rate(beacon_attestations_dropped_total{instance=\"${instance}\",reason=\"Ignore\"}[$__rate_interval])",
     "legendFormat": "attestations (I)"
    },
    {
     "expr": "rate(beacon_aggregates_dropped_total{instance=\"${instance}\",reason=\"Ignore\"}[$__rate_interval])",
     "legendFormat": "aggregates (I)"
    },
    {
     "expr": "rate(beacon_sync_committee_messages_dropped_total{instance=\"${instance}\",reason=\"Ignore\"}[$__rate_interval])",
     "legendFormat": "sync_msgs (I)"
    },
    {
     "expr": "rate(beacon_sync_committee_contributions_dropped_total{instance=\"${instance}\",reason=\"Ignore\"}[$__rate_interval])",
     "legendFormat": "sync_contribs (I)"
    },
    {
     "expr": "rate(beacon_blocks_dropped_total{instance=\"${instance}\",reason=\"Reject\"}[$__rate_interval])",
     "legendFormat": "blocks (R)"
    },
    {
     "expr": "rate(beacon_attestations_dropped_total{instance=\"${instance}\",reason=\"Reject\"}[$__rate_interval])",
     "legendFormat": "attestations (R)"
    },
    {
     "expr": "rate(beacon_aggregates_dropped_total{instance=\"${instance}\",reason=\"Reject\"}[$__rate_interval])",
     "legendFormat": "aggregates (R)"
    },
    {
     "expr": "rate(beacon_sync_committee_messages_dropped_total{instance=\"${instance}\",reason=\"Reject\"}[$__rate_interval])",
     "legendFormat": "sync_msgs (R)"
    },
    {
     "expr": "rate(beacon_sync_committee_contributions_dropped_total{instance=\"${instance}\",reason=\"Reject\"}[$__rate_interval])",
     "legendFormat": "sync_contribs (R)"
    }
   ]
  },
  {
   "title": "Received Attestation Delay (s)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "rate(beacon_attestation_delay_bucket{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Received Aggregate Delay (s)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "rate(beacon_aggregate_delay_bucket{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Received Beacon Block Delay (s)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "rate(beacon_block_delay_bucket{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "storeBlock() Duration (s)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "rate(beacon_store_block_duration_seconds_bucket{namespace=\"$namespace\",pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}