{
 "title": "OpenEthereum",
 "description": "OpenEthereum metrics overview dashboard.",
 "tags": [
  "eth1.0",
  "ethereum",
  "openethereum"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(net_active_peers{}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(net_active_peers{}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sync Status",
   "type": "gauge",
   "description": "WaitingPeers(0), SnapshotManifest(1), SnapshotData(2), SnapshotWaiting(3), Blocks(4), Idle(5), Waiting(6), NewBlocks(7)",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sync_status{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "options": {
    "content": "WaitingPeers(0), SnapshotManifest(1), SnapshotData(2), SnapshotWaiting(3), Blocks(4), Idle(5), Waiting(6), NewBlocks(7)"
   }
  },
  {
   "title": "BlockDetails cache size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchaincache_block_details{namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Blocks imported",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "import_blocks{namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Gas processed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "import_gas{namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Snapshot State",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snapshot_download_chunks_done{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Synced"
    },
    {
     "expr": "snapshot_download_chunks{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Block receipts size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchaincache_block_recipts{namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Transactions applied",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 13, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "import_txs{namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Active peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "net_active_peers{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "net_peers{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DB",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kvdb_reads{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "reads"
    },
    {
     "expr": "kvdb_writes{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchaincache_size{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Cache Size"
    },
    {
     "expr": "chain_block{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Best Block"
    }
   ]
  }
 ]
}