{
 "title": "Prysm",
 "tags": [
  "eth2.0",
  "ethereum",
  "prysm"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(prysm_version{container=\"prysm\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(prysm_version{container=\"prysm\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Beacon Stats",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_current_active_validators{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Active Validators"
    },
    {
     "expr": "beacon_current_justified_epoch{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Current Justified Epoch"
    },
    {
     "expr": "beacon_finalized_epoch{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Finalized Epoch"
    },
    {
     "expr": "beacon_previous_justified_epoch{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Previous Justified Epoch"
    },
    {
     "expr": "beacon_processed_deposits_total{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Processed Deposits"
    },
    {
     "expr": "beacondb_all_deposits{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "All Deposits"
    },
    {
     "expr": "beacondb_pending_deposits{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Pending Deposits"
    },
    {
     "expr": "beacon_reorgs_total{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Reorgs"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_peers{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Peers State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 4 },
   "targets": [
    {
     "expr": "p2p_peer_count{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Peer Subscribed Topics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 4 },
   "targets": [
    {
     "expr": "p2p_subscribed_topic_peer_total{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "GRPC Handled Total",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grpc_server_handled_total{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{grpc_service}} - {{grpc_method}}"
    }
   ]
  },
  {
   "title": "GRPC MSG Received",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grpc_server_msg_received_total{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{grpc_service}} - {{grpc_method}}"
    }
   ]
  },
  {
   "title": "GRPC MSG Sent",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grpc_server_msg_sent_total{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{grpc_service}} - {{grpc_method}}"
    }
   ]
  },
  {
   "title": "Log Entries",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "log_entries_total{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{level}} - {{prefix}}"
    }
   ]
  },
  {
   "title": "P2P MSG Failed Processing",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_message_failed_processing_total{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "P2P MSG Failed Validation",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_message_failed_validation_total{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Validator Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_count{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "P2P MSG Received",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_message_received_total{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "P2P MSG Ignored Validation",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_message_ignored_validation_total{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}